### ISSUE TITLE
Add support for InclusiveGateway

### ISSUE THREAD

**Issue by heyuying99** [bpmn-io/bpmn-js-token-simulation#55]
Problem
When there are InclusiveGateway in the diagram, it's not possible to simulate anything:
![image](https://user-images.githubusercontent.com/22073319/101715538-97418d00-3ad6-11eb-8f1a-04c33df09f88.png)

**Comment by nikku** [comment]
Yes. This is due to the fact that inclusive gateways cannot properly be simulated. They are not properly supported by most process engines, too, cf. [no-inclusive-gateway rule](https://github.com/bpmn-io/bpmnlint/blob/master/docs/rules/no-inclusive-gateway.md).

Please refrain from using them and explicitly model whatever you intend to model with a combination of exclusive and parallel gateways.

Closing this as `won't fix` as we'll not spend time on implementing inclusive gateway support.
