### ISSUE TITLE
Adding attributes to tokens

### ISSUE THREAD

**Issue by hpl002** [bpmn-io/bpmn-js-token-simulation#62]
Hi!

Just stumbled over this project and i can already see that this would be a tremendous tool for the business process simulation community if it were to get a more extensive feature set.

 I might even be interested in working on this myself, but for now i would just like to hear if these are even possible.
 
 ---

**Is the rate at which tokens enter the process configurable in any way? Where is this set?**
 - If this were to be made configurable then the viewer could be used to do token based replay by reading a process log and replaying the events (token flow) as they occur in the log. This is a feature of current defacto tools such as [prom](https://www.promtools.org/doku.php) and [fluxicon disco](https://fluxicon.com/disco/)
 
**Would it be possible to create _complex tokens_?**
 - A complex token is really just a object.
 - Similar to coloured tokens of [colored petri nets](https://cpntools.org/)
- These tokens are then used to determine branching condition. The viewer itself would therefore have to evaluate the expression to determine token flow..
- Current tools only use stochastic distributions to determine branching behavior, which is not ideal for all simulation scenarios. We might have cases where we would like to specify a given input?
- > how does the process perform if given **x** inputs tokens with **y** attributes?

Hope to hear from you!

Herman

**Comment by nikku** [comment]
Hi @hpl002, great for approaching us.

> Is the rate at which tokens enter the process configurable in any way? Where is this set?

Let me elaborate what our tool is and does and what it won't do (in the near future):

When we talk about _simulating_ this is not about throughput analysis, life-lock, dead-lock detection etc. We refer to simulation as you (the user) is able to see the token flow (without an actual thing happening). By doing it you understand / learn the token flow semantics which is crucial knowledge in order to build meaningful diagrams. You see some limitations built into the tool such as the fact that you cannot spawn multiple tokens at the moment. It is partially intentional, as more things happening makes it harder for the user to understand _what_ happens.

For the time being, it is also not meant to be a replay tool (understanding what went wrong, post morten). A simple visualization built on top of [bpmn-js](https://github.com/bpmn-io/bpmn-js) is likely better to accomplish such thing.

> Would it be possible to create complex tokens?

What you're suggesting is to attach data to individual tokens (or make them aware of process instance data) + add an evaluation layer so conditions are dynamically evaluated? I see a few issues with that. If you consider automation, data is not static but rather dynamic, i.e. will be set at certain points in the diagram. To debug _single instance_ behavior we're likely better of to run the process on the real thing, with all behaviors attached (cf. [camunda-playground](https://github.com/nikku/camunda-playground) for example). To analyze the behavior with many instances (i.e. for bottle neck analysis) we're quickly approaching the realm of advanced simulation tools. Likely not a route we're going to take in the near future.

Given that background, what do I plan to do instead?

* Be able to simulate collaboration diagrams, including message flow, both for executable _and_ non-executable pools.
* Be able to spawn multiple tokens _but_ keep _understanding the token flow_ the main priority of the tool.

I hope this somehow makes sense?

**Comment by barmac** [comment]
Hi Herman,

thanks for creating the issue. Can you please update the description according to [the feature request template](https://github.com/bpmn-io/bpmn-js-token-simulation/issues/new?assignees=&labels=enhancement&template=FEATURE_REQUEST.md)? This will help us to understand the use case.

**Comment by hpl002** [comment]
Aha!

I now understand its use and purpose, thank you for the clarification.


---
Something that would be useful but is **unrelated** to this project in particular would be to trace a token flow on the diagram by "replaying" its audit log. I am mentioning this here because i hope that this project might serve as a starting point for such a feature.

Analysis tools such as https://fluxicon.com/disco/ have this feature and it is very useful for visually seeing how the different tokens have progressed through the process over time. I would be happy to try and perform some initial investigation into such a feature if you think that this is a decent starting point.

Would be nice if it could be a stand alone feature too so that a user may simply supply a bpmn file and event log and then have it replayed. Event logs are typically formatted in XES https://xes-standard.org/

**Comment by hpl002** [comment]
Aha!

Thanks for clearing this up!
