### ISSUE TITLE
Exclusive gateways sequence flow color change

### ISSUE THREAD

**Issue by Ichigo85** [bpmn-io/bpmn-js-token-simulation#84]
__Is your feature request related to a problem? Please describe__

I would like to suggest a more visible colour choice for gateway sequence flows. At the moment they are dark grey and light (transparent) grey, but I think, for a user, it would be easier to see them  if they were like green/red. 

__Describe the solution you'd like__

I'd suggest to add visibility to buttons and to the different choices in gateways. Red/Green is just "semaphore conventional", the purpose is to use colours which are "visually intuitive" for a user to understand.

__Describe alternatives you've considered__

I have considered a few choices:
* green/red sequence flows 
* color picker: make the user choose on a small palette
* a small symbol on the "rejected" sequence flows, like an X or something

__Additional context__

Here is the current situation.
![image](https://user-images.githubusercontent.com/27808087/122950174-8a9ecb00-d37c-11eb-8673-e659a13c0e5c.png)

And this is an example of what I mean. I changed the colour of play-buttons, gateway choice and sequence flows. It's visually more 'attractive' and intuitive, I think. 

![image](https://user-images.githubusercontent.com/27808087/122932022-ac448600-d36d-11eb-88d7-94a845f746c6.png)

**Comment by nikku** [comment]
@Ichigo85 What would help a lot is if you could use our existing issue template and provide the relevant context. Maybe put both UI variants (your suggestion and the current one) aside so we can better judge your enhancement request?

Part of our template is also the section _Which alternatives did you consider?_ that is always great to get insights in.

Red and green may not be the perfect choices due to accessibility (red-green blindness) issues. However I'm open for a discussion regarding potential improvements.

**Comment by nikku** [comment]
I personally like the idea of having a small "active" / "rejected" icon on the sequence flow. This could also allow us to activate the sequence flow by clicking on it, rather than toggling through the connected flows.

**Comment by nikku** [comment]
To me it feels like just changing the colors slightly won't improve the accessibility of that feature substantially enough.

**Comment by nikku** [comment]
Closing this issue for the reason mentioned [above](https://github.com/bpmn-io/bpmn-js-token-simulation/issues/84#issuecomment-868398971).
