### ISSUE TITLE
Simulation view doesn't show the relevant buttons for big charts by default (zoom-in needed)

### ISSUE THREAD

**Issue by bhaktichauhan3** [bpmn-io/bpmn-js-token-simulation#86]
__Describe the Bug__

If the chart is big the app scales the view to display it fully but then simulation buttons are not displayed.

__Current Behavior__

At the moment not able to see the Simulation buttons (Start, Switch the flow etc...). We need to zoom-in to get them displayed.

__Expected Behavior__

Simulation feature buttons should be visible all the time no matters the scale of the screen.

**Comment by pinussilvestrus** [comment]
Thanks for reporting! Can you maybe share a screenshot of the situation you are facing? Also sharing your diagram would be very beneficial to us. Thanks!

**Comment by bhaktichauhan3** [comment]
@pinussilvestrus, thank you for taking the time to look at this. Please view the screenshots below; as you can see, the buttons for disable validation are visible even when not zoomed-in, but not for activate simulation.

<img width="435" alt="Validation" src="https://user-images.githubusercontent.com/60789058/128326371-de2d54db-2b12-4da4-984d-5d9776aec35b.png">


https://user-images.githubusercontent.com/60789058/128326047-fc79b2df-fbde-4ae4-b22c-a75382fcd2e6.mov

**Comment by pinussilvestrus** [comment]
Thanks for sharing! I think, different to the [linting plugin](https://github.com/bpmn-io/bpmn-js-bpmnlint) you are probably referring to, the token simulation is defining a [minimal zoom](https://github.com/bpmn-io/bpmn-js-token-simulation/blob/master/lib/features/token-count/TokenCount.js#L109) to show the overlays. 

Therefore the behavior you are describing is intended. Otherwise, I assume, it would be hard to detect which overlay is related to what element.

**Comment by bhaktichauhan3** [comment]
Oh okay that makes sense! @pinussilvestrus  Thanks for pointing me in the right direction.
